### ISSUE TITLE
Create a virtualenv

### ISSUE THREAD

**Issue by mosajjal** [senaps/flasktwitter#1]
Hi.

To make it easier for people to clone your repo, please wrap it inside a virtualenv or better yet, create a requirements.txt file and attach it to your project. 

Don't forget to mention the versions inside it

thanks

**Comment by senaps** [comment]
Hey back.
well there is a requirements.txt attached to the Project.
you can find it in [here](https://github.com/senaps/flasktwitter/blob/master/requirements.txt).
as you can see it's a standard requirements.txt file generated by pip freeze...
i have my own virtual environment for this project, but it wasn't convenience to  wrap that into the project. so you can create you own virtual environment and then clone the repo...
